In [305]:
import pandas as pd
import numpy as np
import sklearn as sk

from functools import reduce
from astral import moon

In [306]:
# Definimos los archivos CSV
archivo_lluvia = './Dataset_INUMET/CSV/Lluvia.csv'
archivo_temperatura = './Dataset_INUMET/CSV/Temperatura.csv'
archivo_humedad = './Dataset_INUMET/CSV/Humedad.csv'
archivo_viento = './Dataset_INUMET/CSV/VientoCarrasco.csv'
archivo_fenomenos = './Dataset_INUMET/CSV/Fenomenos.csv'

# Los cargamos en dataframes
try:
    lluvia_df = pd.read_csv(archivo_lluvia, sep=';')
    temperatura_df = pd.read_csv(archivo_temperatura, sep=';')
    humedad_df = pd.read_csv(archivo_humedad, sep=';')
    viento_df = pd.read_csv(archivo_viento, sep=';')
    fenomenos_df = pd.read_csv(archivo_fenomenos, sep=';')
except Exception as e:
    print(f"Error al leer el archivo CSV: {e}")
    exit()

In [307]:
## Analisis preliminar de los datos
# Debemos determinar el rango de fechas que vamos a utilizar para dataset final
# Para ello, obtenemos la fecha minima y maxima de cada dataframe, que se corresponde con la primer y ultima fila no nula
fechas = {
    'lluvia': (lluvia_df.iloc[0, 2], lluvia_df.iloc[lluvia_df.last_valid_index(), 2]),
    'temperatura': (temperatura_df.iloc[0, 0], temperatura_df.iloc[temperatura_df.last_valid_index(), 0]),
    'humedad': (humedad_df.iloc[0, 0], humedad_df.iloc[humedad_df.last_valid_index(), 0]),
    'viento': (viento_df.iloc[0, 0], viento_df.iloc[viento_df.last_valid_index(), 0]),
    'fenomenos': (fenomenos_df.iloc[0, 0], fenomenos_df.iloc[fenomenos_df.last_valid_index(), 0])
}
# Imprimimos las fechas para ver el rango de cada dataframe
for key in fechas:
    print(f"{key}: {fechas[key][0]} - {fechas[key][1]}")
# Definimos el rango a partir de los datos y nuestras consideraciones (en el informe se explica)
rango = (pd.to_datetime(humedad_df.iloc[0, 0], format='%d/%m/%Y'), pd.to_datetime(lluvia_df.iloc[lluvia_df.last_valid_index() - 1, 2], format='%d/%m/%Y'))
print(f"Rango definido: {rango[0]} - {rango[1]}")

lluvia: 1/1/1950 - 31/7/2025
temperatura: 1/1/1970 - 7/8/2025
humedad: 1/1/1980 - 8/8/2025 23:00
viento: 7/7/1986 08:00 - 8/8/2025 11:00
fenomenos: 1/1/2000 - 11/8/2025 23:00
Rango definido: 1980-01-01 00:00:00 - 2025-07-30 00:00:00

In [308]:
## Lluvias
# Nos quedamos con las filas dentro del rango definido
lluvia_df_subset = lluvia_df[(pd.to_datetime(lluvia_df.iloc[:, 2], format='%d/%m/%Y') >= rango[0])].copy()
lluvia_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y los mm de lluvia
lluvia_df_subset = lluvia_df_subset.iloc[:, [2, 3]]
lluvia_df_subset.columns = ['fecha', 'mm_lluvia']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns])
lluvia_df_subset['fecha'] = pd.to_datetime(lluvia_df_subset['fecha'], format='%d/%m/%Y')
# Verificamos si hay valores no numéricos en lluvia y los reemplazamos por 0, por lo que comentó el profe. Esto se puede hacer para todo el dataset porque reemplazamos por valor constante.
lluvia_df_subset['mm_lluvia'] = pd.to_numeric(lluvia_df_subset['mm_lluvia'], errors='coerce').fillna(0)
# Definimos día lluvioso como los días con lluvias mayores a 1mm
umbral_lluvia = 1.0
lluvia_df_subset['dia_lluvioso'] = (lluvia_df_subset['mm_lluvia'] >= umbral_lluvia).astype(int)

# Creamos la clase objetivo "mañana llueve"
lluvia_df_subset['manana_llueve'] = lluvia_df_subset['dia_lluvioso'].shift(-1)
# Eliminamos la última fila que ahora tiene un valor NaN en 'manana_llueve'
lluvia_df_subset = lluvia_df_subset.dropna(subset=['manana_llueve'])
lluvia_df_subset['manana_llueve'] = lluvia_df_subset['manana_llueve'].astype(int)

print(lluvia_df_subset.head(5))
print(lluvia_df_subset.tail(5))
print("----")
print(lluvia_df_subset.dtypes)

       fecha  mm_lluvia  dia_lluvioso  manana_llueve
0 1980-01-01        0.0             0              0
1 1980-01-02        0.0             0              0
2 1980-01-03        0.0             0              0
3 1980-01-04        0.0             0              1
4 1980-01-05       12.4             1              0
           fecha  mm_lluvia  dia_lluvioso  manana_llueve
16643 2025-07-26        0.0             0              0
16644 2025-07-27        0.0             0              0
16645 2025-07-28        0.0             0              0
16646 2025-07-29        0.0             0              0
16647 2025-07-30        0.0             0              0
----
fecha            datetime64[ns]
mm_lluvia               float64
dia_lluvioso              int64
manana_llueve             int64
dtype: object

In [309]:
## Temperatura
# Nos quedamos con las filas dentro del rango definido
temperatura_df_subset = temperatura_df[(pd.to_datetime(temperatura_df.iloc[:, 0], format='%d/%m/%Y') >= rango[0]) & (pd.to_datetime(temperatura_df.iloc[:, 0], format='%d/%m/%Y') <= rango[1])].copy()
temperatura_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas fecha, Tmax y Tmin de Carrasco
temperatura_df_subset = temperatura_df_subset.iloc[:, :3]
temperatura_df_subset.columns = ['fecha', 'temp_max', 'temp_min']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns])
temperatura_df_subset['fecha'] = pd.to_datetime(temperatura_df_subset['fecha'], format='%d/%m/%Y', errors='coerce')
# Eliminamos filas con fechas inválidas
temperatura_df_subset = temperatura_df_subset.dropna(subset=['fecha'])

# Para categorizar hay que considerar antes valores de todo el dataset. Para hacerlo correctamente primero debemos separar en conjunto de entrenamiento y prueba.
# Se hace más adelante.

print(temperatura_df_subset.head(5))
print(temperatura_df_subset.tail(5))
print("----")
print(temperatura_df_subset.dtypes)

       fecha  temp_max  temp_min
0 1980-01-01      20.0      16.0
1 1980-01-02      26.2      10.7
2 1980-01-03      28.4      15.2
3 1980-01-04      27.2      16.8
4 1980-01-05      29.0      15.6
           fecha  temp_max  temp_min
16643 2025-07-26      13.2       8.8
16644 2025-07-27      12.6       9.0
16645 2025-07-28      13.3       9.9
16646 2025-07-29      15.0       2.2
16647 2025-07-30      18.7       4.8
----
fecha       datetime64[ns]
temp_max           float64
temp_min           float64
dtype: object

In [310]:
## Humedad
# Nos quedamos con las filas dentro del rango definido
humedad_df_subset = humedad_df[(pd.to_datetime(humedad_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') >= rango[0]) & (pd.to_datetime(humedad_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') <= rango[1])].copy()
humedad_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y la humedad relativa de Carrasco
humedad_df_subset = humedad_df_subset.iloc[:,:2].copy()
humedad_df_subset.columns = ['fecha', 'humedad_relativa']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns]), forzando errores a NaT
humedad_df_subset['fecha'] = pd.to_datetime(humedad_df_subset['fecha'], format='%d/%m/%Y %H:%M', errors='coerce')
# Eliminamos filas con fechas no válidas
humedad_df_subset = humedad_df_subset.dropna(subset=['fecha'])
# Transformamos la fecha a solo fecha (sin hora) y lo devolvemos a datetime64[ns] para ser consistentes
humedad_df_subset['fecha'] = humedad_df_subset['fecha'].dt.date
humedad_df_subset['fecha'] = pd.to_datetime(humedad_df_subset['fecha'])
# Agrupamos por dia y calculamos la humedad relativa promedio diaria
humedad_df_subset = humedad_df_subset.groupby('fecha').agg({'humedad_relativa': 'mean'}).reset_index()

# Para categorizar hay que considerar antes valores de todo el dataset. Para hacerlo correctamente primero debemos separar en conjunto de entrenamiento y prueba.
# Se hace más adelante.

print(humedad_df_subset.head(5))
print(humedad_df_subset.tail(5))
print("----")
print(humedad_df_subset.dtypes)

       fecha  humedad_relativa
0 1980-01-01         64.857143
1 1980-01-02         67.428571
2 1980-01-03         61.714286
3 1980-01-04         63.285714
4 1980-01-05         46.142857
           fecha  humedad_relativa
16642 2025-07-25         92.434783
16643 2025-07-26         83.478261
16644 2025-07-27         84.391304
16645 2025-07-28         88.086957
16646 2025-07-29         86.391304
----
fecha               datetime64[ns]
humedad_relativa           float64
dtype: object

In [311]:
## Viento
# Nos quedamos con las filas dentro del rango definido
viento_df_subset = viento_df[(pd.to_datetime(viento_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') >= rango[0]) & (pd.to_datetime(viento_df.iloc[:, 0], format='%d/%m/%Y %H:%M', errors='coerce') <= rango[1])].copy()
viento_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y la dirección del viento de Carrasco
viento_df_subset = viento_df_subset.iloc[:, :2].copy()
viento_df_subset.columns = ['fecha', 'direccion_viento']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns]), forzando errores a NaT
viento_df_subset['fecha'] = pd.to_datetime(viento_df_subset['fecha'], format='%d/%m/%Y %H:%M', errors='coerce')
# Eliminamos filas con fechas no válidas
viento_df_subset = viento_df_subset.dropna(subset=['fecha'])
# Transformamos la fecha a solo fecha (sin hora) y lo devolvemos a datetime64[ns] para ser consistentes
viento_df_subset['fecha'] = viento_df_subset['fecha'].dt.date
viento_df_subset['fecha'] = pd.to_datetime(viento_df_subset['fecha'])
# Creamos funcion para categorizar la dirección del viento de grados a una de las 8 direcciones
def categorizar_direccion_viento(grados):
    if grados is None or pd.isna(grados):
        return np.nan
    try:
        grados = float(grados)
    except (ValueError, TypeError):
        return np.nan
    dirs = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
    ix = round(grados / 45) % 8
    return dirs[ix] 
# La aplicamos al dataframe
viento_df_subset['direccion_viento'] = viento_df_subset['direccion_viento'].apply(categorizar_direccion_viento)
# Aseguramos que categoria sea de tipo category de pandas
viento_df_subset['direccion_viento'] = viento_df_subset['direccion_viento'].astype('category')
# Una vez categorizado, agrupamos por dia y calculamos la dirección del viento predominante diaria
viento_df_subset = viento_df_subset.groupby('fecha').agg({'direccion_viento': lambda x: x.mode()[0] if not x.mode().empty else np.nan}).reset_index()

print(viento_df_subset.head(5))
print(viento_df_subset.tail(5))
print("----")
print(viento_df_subset.dtypes)

       fecha direccion_viento
0 1986-07-07               NE
1 1986-07-08               NE
2 1986-07-09                N
3 1986-07-10                N
4 1986-07-11                N
           fecha direccion_viento
11568 2025-07-26                S
11569 2025-07-27               SE
11570 2025-07-28                S
11571 2025-07-29               NW
11572 2025-07-30              NaN
----
fecha               datetime64[ns]
direccion_viento          category
dtype: object

In [312]:
## Fenómenos
# Nos quedamos con las filas dentro del rango definido
fenomenos_df_subset = fenomenos_df[(pd.to_datetime(fenomenos_df.iloc[:, 0], format='%d/%m/%Y', errors='coerce') >= rango[0]) & (pd.to_datetime(fenomenos_df.iloc[:, 0], format='%d/%m/%Y', errors='coerce') <= rango[1])].copy()
fenomenos_df_subset.reset_index(drop=True, inplace=True)
# Nos quedamos solamente con las columnas de la fecha y el fenómeno
fenomenos_df_subset = fenomenos_df_subset.iloc[:, :2].copy()
fenomenos_df_subset.columns = ['fecha', 'fenomeno']
# Normalizamos el formato de la fecha (pasamos a pandas datetime64[ns])
fenomenos_df_subset['fecha'] = pd.to_datetime(fenomenos_df_subset['fecha'], format='%d/%m/%Y', errors='coerce')
# Eliminamos filas con fechas no válidas
fenomenos_df_subset = fenomenos_df_subset.dropna(subset=['fecha'])
# Transformamos la fecha a solo fecha (sin hora) y lo devolvemos a datetime64[ns] para ser consistentes
fenomenos_df_subset['fecha'] = fenomenos_df_subset['fecha'].dt.date
fenomenos_df_subset['fecha'] = pd.to_datetime(fenomenos_df_subset['fecha'])
# Agrupamos por dia y marcamos si hubo tormenta con truenos (17) ese dia (1 si hubo, 0 si no)
fenomenos_df_subset['hay_truenos'] = fenomenos_df_subset['fenomeno'].apply(lambda x: 1 if x == 17 else 0)
fenomenos_df_subset = fenomenos_df_subset.groupby('fecha').agg({'hay_truenos': 'max'}).reset_index()

print(fenomenos_df_subset.head(5))
print(fenomenos_df_subset.tail(5))
print("----")
print(fenomenos_df_subset.dtypes)

       fecha  hay_truenos
0 2000-01-01            0
1 2000-01-02            0
2 2000-01-03            0
3 2000-01-04            0
4 2000-01-05            0
          fecha  hay_truenos
9338 2025-07-26            0
9339 2025-07-27            0
9340 2025-07-28            0
9341 2025-07-29            0
9342 2025-07-30            0
----
fecha          datetime64[ns]
hay_truenos             int64
dtype: object

In [313]:
## Estación
# Tomamos el dataframe con mayor cantidad de filas (lluvia) como base y nos quedamos con la columna fecha
estacion_df = lluvia_df_subset[['fecha']].copy()
# Creamos funcion para determinar la estación del año según la fecha
def determinar_estacion(fecha):
    mes = fecha.month
    dia = fecha.day
    if (mes == 12 and dia >= 21) or (mes <= 3 and (mes != 3 or dia < 20)):
        return 'Verano'
    elif (mes == 3 and dia >= 20) or (mes <= 6 and (mes != 6 or dia < 21)):
        return 'Otoño'
    elif (mes == 6 and dia >= 21) or (mes <= 9 and (mes != 9 or dia < 22)):
        return 'Invierno'
    else:
        return 'Primavera'
# Creamos la columna estación aplicando la función
estacion_df['estacion'] = estacion_df['fecha'].apply(determinar_estacion)
# Aseguramos que categoria sea de tipo category de pandas
estacion_df['estacion'] = estacion_df['estacion'].astype('category')

print(estacion_df.head(5))
print(estacion_df.tail(5))
print("----")
print(estacion_df.dtypes)

       fecha estacion
0 1980-01-01   Verano
1 1980-01-02   Verano
2 1980-01-03   Verano
3 1980-01-04   Verano
4 1980-01-05   Verano
           fecha  estacion
16643 2025-07-26  Invierno
16644 2025-07-27  Invierno
16645 2025-07-28  Invierno
16646 2025-07-29  Invierno
16647 2025-07-30  Invierno
----
fecha       datetime64[ns]
estacion          category
dtype: object

In [314]:
## Fase lunar
# Tomamos el dataframe con mayor cantidad de filas (lluvia) como base y nos quedamos con la columna fecha
lunar_df = lluvia_df_subset[['fecha']].copy()
# Creamos funcion para determinar la fase lunar según la fecha
def determinar_fase_lunar(fecha):
    dia = moon.phase(fecha)

    if 0 <= dia <= 6:
        return "Luna Nueva"
    elif 7 <= dia <= 13:
        return "Cuarto Creciente"
    elif 14 <= dia <= 20:
        return "Luna Llena"
    else:  # 21–29
        return "Cuarto Menguante"

# Creamos la columna fase lunar aplicando la función
lunar_df['fase_lunar'] = lunar_df['fecha'].apply(determinar_fase_lunar)
# Aseguramos que categoria sea de tipo category de pandas
lunar_df['fase_lunar'] = lunar_df['fase_lunar'].astype('category')

print(lunar_df.head(5))
print(lunar_df.tail(5))
print("----")
print(lunar_df.dtypes)

       fecha        fase_lunar
0 1980-01-01  Cuarto Menguante
1 1980-01-02        Luna Llena
2 1980-01-03        Luna Llena
3 1980-01-04        Luna Llena
4 1980-01-05        Luna Llena
           fecha  fase_lunar
16643 2025-07-26  Luna Nueva
16644 2025-07-27  Luna Nueva
16645 2025-07-28  Luna Nueva
16646 2025-07-29  Luna Nueva
16647 2025-07-30  Luna Nueva
----
fecha         datetime64[ns]
fase_lunar          category
dtype: object

In [315]:
## Merge de todos los dataframes
dataframes = [lluvia_df_subset, temperatura_df_subset, humedad_df_subset, viento_df_subset, fenomenos_df_subset, estacion_df, lunar_df]
merged_preliminar_df = reduce(lambda left, right: pd.merge(left, right, on='fecha', how='outer'), dataframes)
# Ordenamos por fecha
merged_preliminar_df = merged_preliminar_df.sort_values(by='fecha').reset_index(drop=True)

# # Nos quedamos solo con las columnas que nos interesan
# columnas_interes = ['fecha', 'dia_lluvioso', 'temp_categoria_dia', 'humedad_categoria_dia', 'direccion_viento', 'hay_truenos', 'estacion', 'fase_lunar', 'manana_llueve']
# df_merged = df_merged_preliminar[columnas_interes].copy()
# # Corregimos tipos de datos para las columnas con valores binarios
# df_merged['dia_lluvioso'] = df_merged['dia_lluvioso'].astype('Int64')
# df_merged['hay_truenos'] = df_merged['hay_truenos'].astype('Int64')
# df_merged['manana_llueve'] = df_merged['manana_llueve'].astype('Int64')

# print(df_merged.head(50))
# print("----")
# print(df_merged.dtypes)

merged_preliminar_df

## Según el contador de dias de https://onlinealarmkur.com/date/es/
# Hay 27,617 días entre 01/01/1910 y 11/08/2025 (ambos inclusive), es la misma cantidad de filas que tenemos
# Por lo que no hay días faltantes en el dataset final

,fecha,mm_lluvia,dia_lluvioso,manana_llueve,temp_max,temp_min,humedad_relativa,direccion_viento,hay_truenos,estacion,fase_lunar
0,1980-01-01,0.0,0,0,20.0,16.0,64.857143,NaN,NaN,Verano,Cuarto Menguante
1,1980-01-02,0.0,0,0,26.2,10.7,67.428571,NaN,NaN,Verano,Luna Llena
2,1980-01-03,0.0,0,0,28.4,15.2,61.714286,NaN,NaN,Verano,Luna Llena
3,1980-01-04,0.0,0,1,27.2,16.8,63.285714,NaN,NaN,Verano,Luna Llena
4,1980-01-05,12.4,1,0,29.0,15.6,46.142857,NaN,NaN,Verano,Luna Llena
...,...,...,...,...,...,...,...,...,...,...,...
16643,2025-07-26,0.0,0,0,13.2,8.8,83.478261,S,0.0,Invierno,Luna Nueva
16644,2025-07-27,0.0,0,0,12.6,9.0,84.391304,SE,0.0,Invierno,Luna Nueva
16645,2025-07-28,0.0,0,0,13.3,9.9,88.086957,S,0.0,Invierno,Luna Nueva
16646,2025-07-29,0.0,0,0,15.0,2.2,86.391304,NW,0.0,Invierno,Luna Nueva
16647,2025-07-30,0.0,0,0,18.7,4.8,NaN,NaN,0.0,Invierno,Luna Nueva

In [316]:
## Separamos el dataset en conjunto de entrenamiento y prueba
merged_preliminar_X_df = merged_preliminar_df.drop(columns=['manana_llueve'])
merged_preliminar_y_df = merged_preliminar_df['manana_llueve']

# Usamos 80% para entrenamiento y 20% para prueba, usando scikit-learn
entrenamiento_X_df, prueba_X_df, entrenamiento_y_df, prueba_y_df = sk.model_selection.train_test_split(
    merged_preliminar_X_df, merged_preliminar_y_df,
    test_size=0.2,
    random_state=13,
    shuffle=True,
    stratify=merged_preliminar_y_df
)
# Reunimos nuevamente los conjuntos de entrenamiento y prueba
entrenamiento_df = pd.concat([entrenamiento_X_df, entrenamiento_y_df], axis=1).reset_index(drop=True)
prueba_df = pd.concat([prueba_X_df, prueba_y_df], axis=1).reset_index(drop=True)

print(f"Tamaño del conjunto de entrenamiento: {entrenamiento_df.shape}")
print(f"Tamaño del conjunto de prueba: {prueba_df.shape}")
# Verificamos que la proporción de la clase objetivo se mantuvo en ambos conjuntos
print("Proporción de la clase objetivo en el conjunto de entrenamiento:")
print(entrenamiento_df['manana_llueve'].value_counts(normalize=True))
print("Proporción de la clase objetivo en el conjunto de prueba:")
print(prueba_df['manana_llueve'].value_counts(normalize=True))

Tamaño del conjunto de entrenamiento: (13318, 11)
Tamaño del conjunto de prueba: (3330, 11)
Proporción de la clase objetivo en el conjunto de entrenamiento:
manana_llueve
0    0.779697
1    0.220303
Name: proportion, dtype: float64
Proporción de la clase objetivo en el conjunto de prueba:
manana_llueve
0    0.77958
1    0.22042
Name: proportion, dtype: float64

In [317]:
## Ahora sí, podemos categorizar las variables que lo requieren, usando los datos del conjunto de entrenamiento para definir los umbrales
# Temperatura
# Reemplazamos los valores NaN de temperatura por la media de cada columna del conjunto de entrenamiento
temp_max_promedio = entrenamiento_df['temp_max'].mean()
temp_min_promedio = entrenamiento_df['temp_min'].mean()
entrenamiento_df.fillna({'temp_max': temp_max_promedio}, inplace=True)
entrenamiento_df.fillna({'temp_min':temp_min_promedio}, inplace=True)
# Calculamos la temperatura promedio diaria
entrenamiento_df['temp_promedio_dia'] = (entrenamiento_df['temp_max'] + entrenamiento_df['temp_min']) / 2
# Calculamos los umbrales para categorizar la temperatura
max_temp = entrenamiento_df['temp_promedio_dia'].max()
min_temp = entrenamiento_df['temp_promedio_dia'].min()
umbral_alta = min_temp + (max_temp - min_temp) * 2 / 3
umbral_baja = min_temp + (max_temp - min_temp) * 1 / 3
# Creamos funcion para categorizar la temperatura según umbrales en 'Baja', 'Media' y 'Alta'
def categorizar_temperatura(temp):
    if temp < umbral_baja:
        return 'Baja'
    elif umbral_baja <= temp < umbral_alta:
        return 'Media'
    else:
        return 'Alta'
# La aplicamos al dataframe
entrenamiento_df['temp_categoria_dia'] = entrenamiento_df['temp_promedio_dia'].apply(categorizar_temperatura)
# Aseguramos que categoria sea de tipo category de pandas
entrenamiento_df['temp_categoria_dia'] = entrenamiento_df['temp_categoria_dia'].astype('category')

# Humedad relativa
# Reemplazamos los valores NaN de humedad relativa por la media de la columna del conjunto de entrenamiento
humedad_relativa_promedio = entrenamiento_df['humedad_relativa'].mean()
entrenamiento_df.fillna({'humedad_relativa':humedad_relativa_promedio}, inplace=True)
# Calculamos los umbrales para categorizar la humedad relativa en 'Baja', 'Media' y 'Alta'
max_humedad = entrenamiento_df['humedad_relativa'].max()
min_humedad = entrenamiento_df['humedad_relativa'].min()
umbral_alta_hum = min_humedad + (max_humedad - min_humedad) * 2 / 3
umbral_baja_hum = min_humedad + (max_humedad - min_humedad) * 1 / 3
# Creamos funcion para categorizar la humedad relativa en 'Baja', 'Media' y 'Alta'
def categorizar_humedad(hum):
    if hum < umbral_baja_hum:
        return 'Baja'
    elif umbral_baja_hum <= hum < umbral_alta_hum:
        return 'Media'
    else:
        return 'Alta'
# La aplicamos al dataframe
entrenamiento_df['humedad_categoria_dia'] = entrenamiento_df['humedad_relativa'].apply(categorizar_humedad)
# Aseguramos que categoria sea de tipo category de pandas
entrenamiento_df['humedad_categoria_dia'] = entrenamiento_df['humedad_categoria_dia'].astype('category')

# Viento
# Reemplazamos los valores NaN de viento por la moda del mes correspondiente (usando el conjunto de entrenamiento)
# Para ello, extraemos el mes de la fecha y usamos groupby para obtener la moda por mes
entrenamiento_df['mes'] = entrenamiento_df['fecha'].dt.month
moda_viento_por_mes = entrenamiento_df.groupby('mes')['direccion_viento'].agg(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
# Función para reemplazar NaN por la moda del mes
def reemplazar_viento_por_moda(row):
    if pd.isna(row['direccion_viento']):
        return moda_viento_por_mes.get(row['mes'])
    return row['direccion_viento']
# Aplicamos la función al dataframe
entrenamiento_df['direccion_viento'] = entrenamiento_df.apply(reemplazar_viento_por_moda, axis=1)
# Aseguramos que categoria sea de tipo category de pandas
entrenamiento_df['direccion_viento'] = entrenamiento_df['direccion_viento'].astype('category')

# Truenos
# Reemplazamos los valores NaN de hay_truenos por 0 (no hubo truenos)
entrenamiento_df['hay_truenos'] = entrenamiento_df['hay_truenos'].fillna(0).astype(int)

# Imprimimos las filas con valores NaN en el conjunto de entrenamiento para verificar que no haya quedado ninguno
# Contamos los valores NaN en el conjunto de entrenamiento para verificar que no haya quedado ninguno
print("Valores NaN en el conjunto de entrenamiento después de la imputación:")
print(entrenamiento_df.isna().sum())
entrenamiento_df

Valores NaN en el conjunto de entrenamiento después de la imputación:
fecha                    0
mm_lluvia                0
dia_lluvioso             0
temp_max                 0
temp_min                 0
humedad_relativa         0
direccion_viento         0
hay_truenos              0
estacion                 0
fase_lunar               0
manana_llueve            0
temp_promedio_dia        0
temp_categoria_dia       0
humedad_categoria_dia    0
mes                      0
dtype: int64

,fecha,mm_lluvia,dia_lluvioso,temp_max,temp_min,humedad_relativa,direccion_viento,hay_truenos,estacion,fase_lunar,manana_llueve,temp_promedio_dia,temp_categoria_dia,humedad_categoria_dia,mes
0,1990-10-30,0.0,0,22.5,18.6,87.086957,NW,0,Primavera,Cuarto Creciente,0,20.55,Media,Alta,10
1,1989-05-29,0.0,0,19.8,9.0,76.347826,NE,0,Otoño,Cuarto Menguante,0,14.40,Media,Media,5
2,2004-10-10,0.0,0,16.0,13.8,87.565217,SW,0,Primavera,Cuarto Menguante,0,14.90,Media,Alta,10
3,1984-07-04,0.5,0,11.4,4.6,91.391304,N,0,Invierno,Luna Nueva,1,8.00,Baja,Alta,7
4,2002-01-02,0.0,0,25.0,19.0,80.608696,S,0,Verano,Luna Llena,0,22.00,Media,Alta,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13313,1999-03-11,0.0,0,22.0,19.0,69.217391,E,0,Verano,Cuarto Menguante,0,20.50,Media,Media,3
13314,1997-07-16,0.0,0,14.0,3.0,71.000000,N,0,Invierno,Cuarto Creciente,0,8.50,Baja,Media,7
13315,1982-04-24,0.3,0,22.2,15.2,84.130435,N,0,Otoño,Luna Nueva,0,18.70,Media,Alta,4
13316,1983-06-21,1.3,1,14.8,11.6,96.739130,N,0,Invierno,Cuarto Creciente,0,13.20,Media,Alta,6
13317,2022-05-29,0.0,0,11.6,6.0,75.391304,SW,0,Otoño,Cuarto Menguante,0,8.80,Baja,Media,5

In [318]:
# Ahora aplicamos las mismas transformaciones al conjunto de prueba, usando los umbrales y valores calculados en el conjunto de entrenamiento
# Temperatura
# Reemplazamos los valores NaN de temperatura por la media de cada columna del conjunto de entrenamiento
prueba_df.fillna({'temp_max': temp_max_promedio}, inplace=True)
prueba_df.fillna({'temp_min':temp_min_promedio}, inplace=True)
# Calculamos la temperatura promedio diaria
prueba_df['temp_promedio_dia'] = (prueba_df['temp_max'] + prueba_df['temp_min']) / 2
# La aplicamos al dataframe
prueba_df['temp_categoria_dia'] = prueba_df['temp_promedio_dia'].apply(categorizar_temperatura)
# Aseguramos que categoria sea de tipo category de pandas
prueba_df['temp_categoria_dia'] = prueba_df['temp_categoria_dia'].astype('category')

# Humedad relativa
# Reemplazamos los valores NaN de humedad relativa por la media de la columna del conjunto de entrenamiento
prueba_df.fillna({'humedad_relativa':humedad_relativa_promedio}, inplace=True)
# Calculamos los umbrales para categorizar la humedad relativa en 'Baja', 'Media' y 'Alta'
# La aplicamos al dataframe
prueba_df['humedad_categoria_dia'] = prueba_df['humedad_relativa'].apply(categorizar_humedad)
# Aseguramos que categoria sea de tipo category de pandas
prueba_df['humedad_categoria_dia'] = prueba_df['humedad_categoria_dia'].astype('category')

# Viento
# Reemplazamos los valores NaN de viento por la moda del mes correspondiente (usando el conjunto de entrenamiento)
# Para ello, extraemos el mes de la fecha y usamos groupby para obtener la moda por mes
prueba_df['mes'] = prueba_df['fecha'].dt.month
# Aplicamos la función al dataframe
prueba_df['direccion_viento'] = prueba_df.apply(reemplazar_viento_por_moda, axis=1)
# Aseguramos que categoria sea de tipo category de pandas
prueba_df['direccion_viento'] = prueba_df['direccion_viento'].astype('category')

# Truenos
# Reemplazamos los valores NaN de hay_truenos por 0 (no hubo truenos)
prueba_df['hay_truenos'] = prueba_df['hay_truenos'].fillna(0).astype(int)

# Imprimimos las filas con valores NaN en el conjunto de prueba para verificar que no haya quedado ninguno
# Contamos los valores NaN en el conjunto de prueba para verificar que no haya quedado ninguno
print("Valores NaN en el conjunto de prueba después de la imputación:")
print(prueba_df.isna().sum())
prueba_df

Valores NaN en el conjunto de prueba después de la imputación:
fecha                    0
mm_lluvia                0
dia_lluvioso             0
temp_max                 0
temp_min                 0
humedad_relativa         0
direccion_viento         0
hay_truenos              0
estacion                 0
fase_lunar               0
manana_llueve            0
temp_promedio_dia        0
temp_categoria_dia       0
humedad_categoria_dia    0
mes                      0
dtype: int64

,fecha,mm_lluvia,dia_lluvioso,temp_max,temp_min,humedad_relativa,direccion_viento,hay_truenos,estacion,fase_lunar,manana_llueve,temp_promedio_dia,temp_categoria_dia,humedad_categoria_dia,mes
0,1980-08-08,0.0,0,16.0,5.5,66.142857,N,0,Invierno,Cuarto Menguante,0,10.75,Baja,Media,8
1,2020-12-27,0.0,0,26.4,19.4,82.521739,SE,0,Verano,Cuarto Creciente,0,22.90,Alta,Alta,12
2,2016-11-02,2.1,1,16.4,9.1,83.608696,W,0,Primavera,Luna Nueva,0,12.75,Media,Alta,11
3,2017-03-11,1.0,1,25.4,11.4,63.304348,N,0,Verano,Cuarto Creciente,0,18.40,Media,Media,3
4,1999-04-14,0.0,0,24.2,11.0,75.434783,N,0,Otoño,Cuarto Menguante,1,17.60,Media,Media,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3325,2021-10-19,0.0,0,20.2,6.0,77.391304,SE,0,Primavera,Cuarto Menguante,0,13.10,Media,Media,10
3326,1982-02-07,0.0,0,30.0,16.8,63.434783,SE,0,Verano,Cuarto Menguante,1,23.40,Alta,Media,2
3327,2021-03-13,0.0,0,23.4,12.0,72.043478,S,0,Verano,Luna Nueva,0,17.70,Media,Media,3
3328,1981-11-03,0.1,0,20.0,16.6,94.714286,SE,0,Primavera,Luna Nueva,1,18.30,Media,Alta,11
3329,2002-08-30,0.0,0,11.2,7.5,64.086957,W,0,Invierno,Cuarto Menguante,1,9.35,Baja,Media,8

In [319]:
# Nos quedamos solo con las columnas que nos interesan
columnas_interes_m1 = ['fecha', 'dia_lluvioso', 'temp_categoria_dia', 'humedad_categoria_dia', 'direccion_viento', 'estacion', 'manana_llueve']
columnas_interes_m2 = columnas_interes_m1 + ['hay_truenos', 'fase_lunar']

entrenamiento_final_m1_df = entrenamiento_df[columnas_interes_m1].copy()
prueba_final_m1_df = prueba_df[columnas_interes_m1].copy()

entrenamiento_final_m2_df = entrenamiento_df[columnas_interes_m2].copy()
prueba_final_m2_df = prueba_df[columnas_interes_m2].copy()

In [320]:
entrenamiento_final_m1_df

,fecha,dia_lluvioso,temp_categoria_dia,humedad_categoria_dia,direccion_viento,estacion,manana_llueve
0,1990-10-30,0,Media,Alta,NW,Primavera,0
1,1989-05-29,0,Media,Media,NE,Otoño,0
2,2004-10-10,0,Media,Alta,SW,Primavera,0
3,1984-07-04,0,Baja,Alta,N,Invierno,1
4,2002-01-02,0,Media,Alta,S,Verano,0
...,...,...,...,...,...,...,...
13313,1999-03-11,0,Media,Media,E,Verano,0
13314,1997-07-16,0,Baja,Media,N,Invierno,0
13315,1982-04-24,0,Media,Alta,N,Otoño,0
13316,1983-06-21,1,Media,Alta,N,Invierno,0
13317,2022-05-29,0,Baja,Media,SW,Otoño,0

In [321]:
prueba_final_m1_df

,fecha,dia_lluvioso,temp_categoria_dia,humedad_categoria_dia,direccion_viento,estacion,manana_llueve
0,1980-08-08,0,Baja,Media,N,Invierno,0
1,2020-12-27,0,Alta,Alta,SE,Verano,0
2,2016-11-02,1,Media,Alta,W,Primavera,0
3,2017-03-11,1,Media,Media,N,Verano,0
4,1999-04-14,0,Media,Media,N,Otoño,1
...,...,...,...,...,...,...,...
3325,2021-10-19,0,Media,Media,SE,Primavera,0
3326,1982-02-07,0,Alta,Media,SE,Verano,1
3327,2021-03-13,0,Media,Media,S,Verano,0
3328,1981-11-03,0,Media,Alta,SE,Primavera,1
3329,2002-08-30,0,Baja,Media,W,Invierno,1

In [322]:
def calcular_probabilidad(df, col, valor, clase, m):
    # Filtrar el DataFrame por la clase
    df_clase = df[df['manana_llueve'] == clase]
    cant_elementos = len(df_clase)
    p=1/len(df_clase[col].unique())
    # Calcular la probabilidad
    if(cant_elementos == 0):
        print("No hay elementos de la clase ", clase, " para calcular la probabilidad")
        return 0
    #Utilizamos m-estimador (e + m * p) / (n + m)
    return ((df_clase[col].value_counts().get(valor, 0) + m *p) / (cant_elementos + m))

In [323]:
# Implementación Naive Bayes

# Modelo es una lista de 2 listas, la primera corresponde a la clase 0 y la segunda a la clase 1. 
# Cada sublista contiene tuplas (nombre columna, valor posible, probabilidad)
modelo = []

# m para m-estimador
m = 5

# Probabilidades P(Vj) - Iniciales para cada clase
prob0 = len(entrenamiento_final_m1_df[entrenamiento_final_m1_df['manana_llueve'] == 0]) / len(entrenamiento_final_m1_df)
prob1 = 1 - prob0
prob_iniciales = [prob0, prob1]
print(f"Probabilidades iniciales: {prob_iniciales}")

#Para cada clase objetivo recorro todas las columnas y sus valores posibles para calcular P(Atributo=valor|Clase)
for i in range(2):
    modelo.append([])
    for col in entrenamiento_final_m1_df.columns:
        if col != 'fecha' and col != 'manana_llueve':
            # Columnas categóricas
            if entrenamiento_final_m1_df[col].dtype.name == 'category':
                valores_posibles = entrenamiento_final_m1_df[col].cat.categories.tolist()
            else:
                # Columnas numéricas
                valores_posibles = entrenamiento_final_m1_df[col].unique().tolist()
            for valor in valores_posibles:
                prob = calcular_probabilidad(entrenamiento_final_m1_df, col, valor, i, m)
                modelo[i].append((col, valor, prob))

# Imprimimos el modelo
for i in range(2):
    print(f"Probabilidades para la clase {i}:")
    for item in modelo[i]:
        print(item)
    print("----")

Probabilidades iniciales: [0.7796966511488211, 0.22030334885117886]
Probabilidades para la clase 0:
('dia_lluvioso', 0, np.float64(0.825536625276735))
('dia_lluvioso', 1, np.float64(0.17446337472326498))
('temp_categoria_dia', 'Alta', np.float64(0.12837295857798314))
('temp_categoria_dia', 'Baja', np.float64(0.2847883979850483))
('temp_categoria_dia', 'Media', np.float64(0.5868386434369686))
('humedad_categoria_dia', 'Alta', np.float64(0.39615619084287873))
('humedad_categoria_dia', 'Baja', np.float64(0.06609554978021626))
('humedad_categoria_dia', 'Media', np.float64(0.5377482593769051))
('direccion_viento', 'E', np.float64(0.11479690056790837))
('direccion_viento', 'N', np.float64(0.2912335162190779))
('direccion_viento', 'NE', np.float64(0.08447636923669266))
('direccion_viento', 'NW', np.float64(0.04789922032919434))
('direccion_viento', 'S', np.float64(0.11229425353739532))
('direccion_viento', 'SE', np.float64(0.24127683126383676))
('direccion_viento', 'SW', np.float64(0.06002743286168062))
('direccion_viento', 'W', np.float64(0.047995475984214074))
('estacion', 'Invierno', np.float64(0.2562566175762826))
('estacion', 'Otoño', np.float64(0.25616036192126285))
('estacion', 'Primavera', np.float64(0.24047069015304648))
('estacion', 'Verano', np.float64(0.24711233034940802))
----
Probabilidades para la clase 1:
('dia_lluvioso', 0, np.float64(0.6105818305546105))
('dia_lluvioso', 1, np.float64(0.3894181694453896))
('temp_categoria_dia', 'Alta', np.float64(0.1887263241465351))
('temp_categoria_dia', 'Baja', np.float64(0.1826017919927413))
('temp_categoria_dia', 'Media', np.float64(0.6286718838607236))
('humedad_categoria_dia', 'Alta', np.float64(0.50482023363956))
('humedad_categoria_dia', 'Baja', np.float64(0.046501077463990015))
('humedad_categoria_dia', 'Media', np.float64(0.4486786888964501))
('direccion_viento', 'E', np.float64(0.16931779516842463))
('direccion_viento', 'N', np.float64(0.28942667574004766))
('direccion_viento', 'NE', np.float64(0.13223035045933992))
('direccion_viento', 'NW', np.float64(0.023009527050017013))
('direccion_viento', 'S', np.float64(0.0669020074855393))
('direccion_viento', 'SE', np.float64(0.27513610071452876))
('direccion_viento', 'SW', np.float64(0.025731541340592037))
('direccion_viento', 'W', np.float64(0.01824600204151072))
('estacion', 'Invierno', np.float64(0.24710785981626404))
('estacion', 'Otoño', np.float64(0.26922422592718614))
('estacion', 'Primavera', np.float64(0.24030282408982648))
('estacion', 'Verano', np.float64(0.24336509016672336))
----

In [324]:
def predecir_clase(fila, modelo):
    prob_clases = [1, 1]
    for i in range(2):
        for col in fila.index:
            if col != 'fecha' and col != 'manana_llueve':
                valor = fila[col]
                # Buscar la probabilidad correspondiente en el modelo
                prob = None
                for item in modelo[i]:
                    if item[0] == col and item[1] == valor:
                        prob = item[2]
                        break
                prob_clases[i] *= prob
        # Multiplicamos por la probabilidad de la clase
        prob_clases[i] *= prob_iniciales[i]

    # Devolvemos la clase con mayor probabilidad
    if(prob_clases[0]>prob_clases[1]):
        return 0
    else:
        return 1

In [325]:
y_true = []
y_pred = []
for i in prueba_final_m1_df.index:
    fila = prueba_final_m1_df.loc[i]
    clase_pred = predecir_clase(fila, modelo)
    #print(f"Fila {i}: Real {fila['manana_llueve']} Predicha = {clase_pred}")
    y_true.append(fila['manana_llueve'])
    y_pred.append(clase_pred)


# Evaluamos el modelo
precision = sk.metrics.precision_score(y_true, y_pred)
recall = sk.metrics.recall_score(y_true, y_pred)
print(f"Precisión: {precision:.4f}")
print(f"Recall: {recall:.4f}")

Precisión: 0.4530
Recall: 0.1117

In [326]:
#print(entrenamiento_final_m1_df.head())
#print(f"\nTipos de datos: {entrenamiento_final_m1_df.dtypes}")
#entrenamiento_final_m1_df['dia_lluvioso'] = entrenamiento_final_m1_df['dia_lluvioso'].astype('category')
#entrenamiento_final_m1_df['manana_llueve'] = entrenamiento_final_m1_df['manana_llueve'].astype('category')

In [336]:
entrenamiento_encoded = entrenamiento_final_m1_df.drop(columns=['fecha', 'manana_llueve']).copy()
prueba_encoded = prueba_final_m1_df.drop(columns=['fecha', 'manana_llueve']).copy()

def encode(str):
    if str == 'Baja' or str == 'N' or str == "Verano":
        return 0
    elif str == 'Media' or str == 'NE' or str == 'Otoño':
        return 1
    elif str == 'Alta' or str == 'E' or str == 'Invierno':
        return 2
    elif str == 'SE' or str == 'Primavera':
        return 3
    elif str == 'S':
        return 4
    elif str == 'SW':
        return 5
    elif str == 'W':
        return 6
    elif str == 'NW':
        return 7
    
#Aplicamos la función de encoding a todas las columnas categóricas
for col in entrenamiento_encoded.columns:
    if entrenamiento_encoded[col].dtype.name == 'category':
        entrenamiento_encoded[col] = entrenamiento_encoded[col].apply(encode)
        prueba_encoded[col] = prueba_encoded[col].apply(encode)

print(entrenamiento_encoded.head())
print(prueba_encoded.head())

   dia_lluvioso temp_categoria_dia humedad_categoria_dia direccion_viento  \
0             0                  1                     2                7
1             0                  1                     1                1
2             0                  1                     2                5
3             0                  0                     2                0
4             0                  1                     2                4

  estacion
0        3
1        1
2        3
3        2
4        0
   dia_lluvioso temp_categoria_dia humedad_categoria_dia direccion_viento  \
0             0                  0                     1                0
1             0                  2                     2                3
2             1                  1                     2                6
3             1                  1                     1                0
4             0                  1                     1                0

  estacion
0        2
1        0
2        3
3        0
4        1

In [337]:
##Duplicar filas del df que tengan manana_llueve = 1 para balancear el dataset
entrenamiento_encoded['manana_llueve'] = entrenamiento_final_m1_df['manana_llueve']
# Duplicar filas que tengan manana_llueve = 1 2 veces
entrenamiento_encoded = pd.concat([entrenamiento_encoded, entrenamiento_encoded[entrenamiento_encoded['manana_llueve'] == 1]] * 2, ignore_index=True)

prob0 = len(entrenamiento_encoded[entrenamiento_encoded['manana_llueve'] == 0]) / len(entrenamiento_encoded)
prob1 = 1 - prob0

print(f"Probabilidades iniciales después de balancear: {[prob0, prob1]}")

entrenamiento_encoded_mas = entrenamiento_encoded.drop(columns=['manana_llueve']).copy()

Probabilidades iniciales después de balancear: [0.6389367462466158, 0.3610632537533842]

In [340]:
# Naive Bayes con CategoricalNB
from sklearn.naive_bayes import CategoricalNB

# Creamos el modelo
nb_model = CategoricalNB()
# Entrenamos el modelo
nb_model.fit(entrenamiento_encoded_mas, entrenamiento_encoded['manana_llueve'])
# Hacemos predicciones
predicciones = nb_model.predict(prueba_encoded)
# Evaluamos el modelo
precision_nb = sk.metrics.precision_score(prueba_final_m1_df['manana_llueve'], predicciones)
recall_nb = sk.metrics.recall_score(prueba_final_m1_df['manana_llueve'], predicciones)
f1_nb = sk.metrics.f1_score(prueba_final_m1_df['manana_llueve'], predicciones)
accuracy_nb = sk.metrics.accuracy_score(prueba_final_m1_df['manana_llueve'], predicciones)

print(f"\nResultados CategoricalNB:")
print(f"Precisión: {precision_nb:.4f}")
print(f"Recall: {recall_nb:.4f}")
print(f"F1-Score: {f1_nb:.4f}")
print(f"Accuracy: {accuracy_nb:.4f}")

Resultados CategoricalNB:
Precisión: 0.4266
Recall: 0.3365
F1-Score: 0.3762
Accuracy: 0.7541